contracts_folder: tests/data/contracts/ethereum/local

ethereum:
  mainnet:
    default_provider: node
  local:
    default_provider: foundry

polygon:
  local:
    default_provider: foundry
  amoy:
    default_provider: node
  mainnet:
    default_provider: node

node:
  ethereum:
    mainnet:
      uri: https://ethereum.publicnode.com
    sepolia:
      uri: https://ethereum-sepolia-rpc.publicnode.com
    holesky:
      uri: https://ethereum-holesky-rpc.publicnode.com
  polygon:
    amoy:
      uri: https://polygon-amoy-bor-rpc.publicnode.com
    mainnet:
      uri: https://polygon-bor-rpc.publicnode.com

foundry:
  request_timeout: 29
  fork_request_timeout: 360
  priority_fee: 0
  base_fee: 0

  fork:
    ethereum:
      mainnet:
        upstream_provider: https://ethereum.publicnode.com
        block_number: 21418244
      sepolia:
        upstream_provider: https://ethereum-sepolia-rpc.publicnode.com
        block_number: 3091950
      holesky:
        upstream_provider: https://ethereum-holesky-rpc.publicnode.com
        block_number: 100

test:
  # `false` because running pytest within pytest.
  disconnect_providers_after: false

  gas:
    exclude:
      - method_name: setAdd*

  balance: 100_000 ETH
